using Microsoft.EntityFrameworkCore;

namespace backend;

public static class DatabaseSchemaBootstrap
{
    public static async Task EnsureAsync(
        EnergyDbContext db
    )
    {
        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "GenerationRecords"
            ADD COLUMN IF NOT EXISTS "CountryName"
                character varying(100) NOT NULL DEFAULT '';

            ALTER TABLE "GenerationRecords"
            ADD COLUMN IF NOT EXISTS "ZonesAggregatedJson"
                text NOT NULL DEFAULT '[]';

            CREATE TABLE IF NOT EXISTS "GenerationChartPoints" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "IsoCode" character varying(10) NOT NULL,
                "CountryName" character varying(100) NOT NULL,
                "PeriodType" character varying(20) NOT NULL,
                "PeriodStart" timestamp with time zone NOT NULL,
                "PeriodEnd" timestamp with time zone NOT NULL,
                "Total" double precision NOT NULL,
                "RenewableMw" double precision NOT NULL,
                "RenewablePct" double precision NOT NULL,
                "WindMw" double precision NOT NULL,
                "SolarMw" double precision NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_GenerationChartPoints" PRIMARY KEY ("Id")
            );

            CREATE UNIQUE INDEX IF NOT EXISTS
                "IX_GenerationChartPoints_IsoCode_PeriodType_PeriodStart"
            ON "GenerationChartPoints" ("IsoCode", "PeriodType", "PeriodStart");

            CREATE INDEX IF NOT EXISTS
                "IX_GenerationRecords_IsoCode_FetchedAt"
            ON "GenerationRecords" ("IsoCode", "FetchedAt");
            """);
    }
}
