using System.Text;
using backend;
using backend.Repositories;
using backend.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Npgsql;

if (File.Exists(".env"))
{
    DotNetEnv.Env.Load();
}

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowReact", policy =>
    {
        policy
            .WithOrigins(
                "http://localhost:5173",
                "http://localhost:5174",
                "http://localhost:3000")
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

builder.Services.AddDbContext<EnergyDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddScoped<IGenerationRepository, GenerationRepository>();
builder.Services.AddScoped<IHistoryRepository, HistoryRepository>();
builder.Services.AddScoped<IPreferencesRepository, PreferencesRepository>();
builder.Services.AddScoped<GenerationService>();
builder.Services.AddScoped<HistoryService>();
builder.Services.AddScoped<PreferencesService>();
builder.Services.AddScoped<AuthService>();
builder.Services.Configure<backend.Models.EmailOptions>(
    builder.Configuration.GetSection(backend.Models.EmailOptions.SectionName));
builder.Services.AddScoped<IEmailService, EmailService>();
builder.Services.AddHttpClient<EntsoeService>();
builder.Services.AddHostedService<EntsoeDataSyncService>();

var jwtKey = builder.Configuration["Jwt:Key"]
    ?? Environment.GetEnvironmentVariable("JWT_SECRET")
    ?? "green-energy-monitor-dev-jwt-key-change-me-32chars!";

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"] ?? "green-energy-monitor",
            ValidAudience = builder.Configuration["Jwt:Audience"] ?? "green-energy-monitor",
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)),
        };
    });

builder.Services.AddAuthorization();

builder.Services.AddCors(options =>
{
    options.AddPolicy("PermiteTot", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});

var app = builder.Build();
app.UseCors("PermiteTot");

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseAuthentication();
app.UseAuthorization();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<EnergyDbContext>();

    try
    {
        await db.Database.MigrateAsync();
    }
    catch (PostgresException ex) when (ex.SqlState is "42701" or "42P07")
    {
        // Handles databases where schema objects were created manually before migrations ran.
        await db.Database.ExecuteSqlInterpolatedAsync($"""
            INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
            VALUES ({"20260713131344_AddSnapshotFieldsAndChartPoints"}, {"9.0.4"})
            ON CONFLICT ("MigrationId") DO NOTHING
            """);
    }

    await EnsureViewerTimezoneTableAsync(db);
    await EnsureUsersTableAsync(db);
    await EnsureReferenceDataAsync(db);
}

app.MapControllers();
app.Run();

static async Task EnsureViewerTimezoneTableAsync(EnergyDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "ViewerTimezonePreferences" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ClientId" character varying(100) NOT NULL,
            "CountryIso" character varying(10) NOT NULL,
            "TimeZone" character varying(100) NOT NULL,
            "UpdatedAt" timestamp with time zone NOT NULL
        );

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_ViewerTimezonePreferences_ClientId"
            ON "ViewerTimezonePreferences" ("ClientId");
        """);
}

static async Task EnsureUsersTableAsync(EnergyDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "Users" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Email" character varying(256) NOT NULL,
            "DisplayName" character varying(100) NOT NULL,
            "Gender" character varying(20) NOT NULL DEFAULT 'Male',
            "PasswordHash" character varying(200) NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        );

        ALTER TABLE "Users"
            ADD COLUMN IF NOT EXISTS "Gender" character varying(20) NOT NULL DEFAULT 'Male';

        ALTER TABLE "Users"
            ADD COLUMN IF NOT EXISTS "PasswordResetTokenHash" character varying(128) NULL;

        ALTER TABLE "Users"
            ADD COLUMN IF NOT EXISTS "PasswordResetTokenExpiresAt" timestamp with time zone NULL;

        CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email"
            ON "Users" ("Email");

        CREATE INDEX IF NOT EXISTS "IX_Users_PasswordResetTokenHash"
            ON "Users" ("PasswordResetTokenHash");
        """);
}

static async Task EnsureReferenceDataAsync(EnergyDbContext db)
{
    var existingZones = await db.CountryZones
        .Select(zone => new { zone.IsoCode, zone.ZoneCode })
        .ToListAsync();

    var existingZoneKeys = existingZones
        .Select(zone => (zone.IsoCode.ToUpperInvariant(), zone.ZoneCode))
        .ToHashSet();

    foreach (var (iso, zoneCodes) in CountryCatalog.ZoneCodes)
    {
        foreach (var zoneCode in zoneCodes)
        {
            if (existingZoneKeys.Contains((iso, zoneCode)))
            {
                continue;
            }

            db.CountryZones.Add(new backend.Models.CountryZone
            {
                IsoCode = iso,
                ZoneCode = zoneCode,
            });
        }
    }

    var existingSourceCodes = await db.EnergySources
        .Select(source => source.Code)
        .ToListAsync();

    var existingSourceSet = existingSourceCodes
        .Select(code => code.ToUpperInvariant())
        .ToHashSet();

    foreach (var (code, source) in CountryCatalog.EnergySources)
    {
        if (existingSourceSet.Contains(code.ToUpperInvariant()))
        {
            continue;
        }

        db.EnergySources.Add(new backend.Models.EnergySource
        {
            Code = code,
            Name = source.Name,
            IsRenewable = source.Renewable,
        });
    }

    if (db.ChangeTracker.HasChanges())
    {
        await db.SaveChangesAsync();
    }
}
