// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    [Migration("20260713103902_FinalGenerationRecordFix")]
    partial class FinalGenerationRecordFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.CountryZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CountryZones");
                });

            modelBuilder.Entity("backend.Models.EnergySource", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<bool>("IsRenewable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("EnergySources");
                });

            modelBuilder.Entity("backend.Models.GenerationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BySourceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryIso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnergySourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnergySourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRenewable")
                        .HasColumnType("boolean");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RenewableMw")
                        .HasColumnType("double precision");

                    b.Property<double>("RenewablePct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.Property<double>("ValueMw")
                        .HasColumnType("double precision");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GenerationRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
